config/routes.rb
Rails.application.routes.draw do
  resources :workers
  devise_for :users,
    controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
end

app/models/worker.rb
class Worker < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @todo = YAML.load_file(Rails.root.join("todo_list.yml"))
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(
      :name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(
      :name, :last_name, :email, :password, :password_confirmation,
      :current_password)
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  def create
    @worker = Worker.new(worker_params)

    if @worker.save
      redirect_to @worker, notice: 'Worker was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /workers/1
  def update
    if @worker.update(worker_params)
      redirect_to @worker, notice: 'Worker was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /workers/1
  def destroy
    @worker.destroy
    redirect_to workers_url, notice: 'Worker was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def worker_params
      params.require(:worker).permit(:name, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_name
    "#{current_user.name} #{current_user.last_name}"
  end

  def time_greeting
    greet = "Buen"
    case Time.now.hour
    when 0..4
      greet += "as noches"
    when 5..11
      greet += "os días"
    when 12..20
      greet += "as tardes"
    when 21..23
      greet += "as noches"
    end
    greet
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/dashboard/index.html.slim
h4
  small = "#{time_greeting},"
  = full_name
h1
  em Me llaman Octubre

.row
  .col-sm-12.col-md-8
    h2
      | Logros
      small Cosas por hacer y por cambiar

    ul
      - @todo[:tasks].each do |task|
        li == task

  .col-sm-12.col-md
    h3 ¿Por qué "Octubre"?
    p Es una canción de Love of Lesbian de apenas dos minutos.
    p
      a.button href="https://www.youtube.com/watch?v=1gaA8IhWaB4" Youtube
      a.button href="https://open.spotify.com/track/4yxkZilPRSASU8PskCXS1y?si=FdDwJ97DTOWY-VM4wR5wxg" Spotify
      a.button href="https://itunes.apple.com/mx/album/me-llaman-octubre/1273111488?i=1273111787" Apple Music

app/views/layouts/_header.html.slim
header class="row"
  = link_to "Octubre", root_path, class: "logo col-sm col-md-2"
  a.button.col-sm.col-md-2 Botón 1
  a.button.col-sm.col-md-2 Botón 2
  a.button.col-sm.col-md-2 Botón 3
  - if user_signed_in?
    = link_to "logout", destroy_user_session_path, method: :delete, class: "button col-sm col-md-2"

app/views/layouts/application.html.slim
doctype html
html
  head
    title Octubre
    = csrf_meta_tags
    = csp_meta_tag

    /= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    link rel="stylesheet" href="https://cdn.rawgit.com/Chalarangelo/mini.css/v3.0.0/dist/mini-default.min.css"
    meta name="viewport" content="width=device-width, initial-scale=1"
  body
    = render 'layouts/header'
    main.container
      .row
        .col-sm.col-md-10.col-md-offset-1.col-lg-8.col-lg-offset-2
          = yield

app/views/workers/_form.html.slim
= simple_form_for(@worker) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :phone

  .form-actions
    = f.button :submit

app/views/workers/edit.html.slim
h1 Editing worker

== render 'form'

=> link_to 'Show', @worker
'|
=< link_to 'Back', workers_path

app/views/workers/index.html.slim
h1 Listing workers

table
  thead
    tr
      th Name
      th Phone
      th
      th
      th

  tbody
    - @workers.each do |worker|
      tr
        td = worker.name
        td = worker.phone
        td = link_to 'Show', worker
        td = link_to 'Edit', edit_worker_path(worker)
        td = link_to 'Destroy', worker, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Worker', new_worker_path

app/views/workers/new.html.slim
h1 New worker

== render 'form'

= link_to 'Back', workers_path

app/views/workers/show.html.slim
p#notice = notice

p
  strong Name:
  = @worker.name
p
  strong Phone:
  = @worker.phone

=> link_to 'Edit', edit_worker_path(@worker)
'|
=< link_to 'Back', workers_path